name: Test-Chunks
version: 0.39
abstract: A Data Driven Testing Framework
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Test::Base: 0.40
  Spiffy: 0.24
  Test::More: 0.54
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
